apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "*/2 * * * *" # Runs backup every two minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            access: "true"
        spec:
          containers:
            - name: mongodump
              image: mongo
              command:
                - sh
                - -c
                - |
                  # Perform backup
                  mongodump --host=$MONGODB_HOSTNAME --port=27017 --out=/backup/$(date +\%Y-\%m-\%dT\%H-\%M-\%S) --username $MONGODB_ROOT_USERNAME --password $MONGODB_ROOT_PASSWORD
                  # Remove backups older than 7 days
                  find /backup -type d -mtime +7 -exec rm -rf {} +
              env:
                - name: MONGODB_ROOT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-secret
                      key: mongo-root-username
                - name: MONGODB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-secret
                      key: mongo-root-password
                - name: MONGODB_HOSTNAME
                  valueFrom:
                    configMapKeyRef:
                      name: mongodb-configmap
                      key: database_url
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: Never
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-pvc
