apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-mongodb
spec:
  podSelector:
    matchLabels:
      app: mongodb
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: "true"
      ports:
        - protocol: TCP
          port: 27017
