apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sfs
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo-sfs
  template:
    metadata:
      labels:
        app: mongo-sfs
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
            - name: keyfile
              mountPath: /etc/mongodb-keyfile
              readOnly: true
      volumes:
        - name: keyfile
          secret:
            secretName: mongodb-keyfile
            defaultMode: 0400
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "fast-storage"
        resources:
          requests:
            storage: 5Gi
