apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sfs
spec:
  serviceName: mongo-sfs-service
  replicas: 3
  selector:
    matchLabels:
      app: mongo-sfs
  template:
    metadata:
      labels:
        app: mongo-sfs
    spec:
      containers:
        - name: mongo-sfs
          image: mongo
          command:
            - mongod
            - "--replSet" # --replSet <setname>: Configures replication.
            - rs0
            - "--bind_ip_all" # --bind_ip_all: the mongod instance binds to all IPv4 addresses
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
            - name: keyfile
              mountPath: /etc/mongodb-keyfile
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: keyfile
          secret:
            secretName: mongodb-keyfile
            defaultMode: 0400
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: servertype
                operator: In
                values:
                - mongodb
      tolerations:
      - key: "servertype"
        operator: "Equal"
        value: "nginx"
        effect: "NoSchedule"
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "fast-storage"
        resources:
          requests:
            storage: 5Gi
