apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate