# If the multi-target mode is enabled, this value will be ignored.
# [mongodb[+srv]://][user:pass@]host1[:port1][,host2[:port2],...][/database][?options]
mongodb:
  uri: "mongodb://mongodb-service.development.svc.cluster.local:27017"

# Name of an externally managed secret (in the same namespace) containing the connection uri as key `mongodb-uri`.
# If this is provided, the value mongodb.uri is ignored.
existingSecret:
  name: mongodb-secret
  key: mongodb-uri

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels:
    release: kube-prometheus-stack

extraArgs:
  - --collector.diagnosticdata
  - --collector.replicasetstatus
  - --collector.dbstats
  - --collector.topmetrics
  - --collector.indexstats
  - --collector.collstats
  - --collector.dbstatsfreestorage
  - --collector.currentopmetrics
  - --collector.fcv
  - --log.level=debug

