apiVersion: v1
kind: Service
metadata:
  name: grafana-ext-service
spec:
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  type: NodePort
  ports:
  - nodePort: 31825
    port: 80
    protocol: TCP
    targetPort: 3000