apiVersion: v1
kind: Service
metadata:
  name: mongo-sfs-service
  labels:
    app: mongo-sfs-service
spec:
  clusterIP: None
  selector:
    app: mongo-sfs
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017