apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-ext-service
spec:
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: kube-prometheus-stack-prometheus
  type: NodePort
  ports:
    - nodePort: 30517
      port: 80
      protocol: TCP
      targetPort: 9090
