apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  containers:
  - image: alpine:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always