apiVersion: v1 
kind: Pod 
metadata:
  name: backup-access
  labels:
    app: backup-access
    access: "true"
spec:
  containers:
    - name: mongodb
      image: mongo
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: backup-storage
          mountPath: /backup
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "1"
  volumes:
    - name: backup-storage
      persistentVolumeClaim:
        claimName: backup-pvc
  priorityClassName: medium