# Rename the file to mongodb-secret.yaml
apiVersion: v1
kind: Secret 
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  # get base64 encoded value for mongodb://username:password@mongodb-service.development.svc.cluster.local:27017
  mongodb-uri: